name: CI tests
on:
  - push

jobs:

  unittest:
    runs-on: ubuntu-22.04
    container: python:3.10
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: pip install -r requirements-dev.txt
      # install dependencies mentioned in pyproject.toml
      - run: pip install .
      - name: Wait on keycloak to be up
        run: curl -k --connect-timeout 60 --retry 60 --retry-delay 1 --retry-connrefused --retry-max-time 60 $KC_ENDPOINT -v
      # At least it should not crash
      - run: python -m unittest
    env:
      # KEYCLOAK_API_CA_BUNDLE:
      # KC_ENDPOINT: https://keycloak:8443
      KC_ENDPOINT: http://keycloak:8080
      KC_USER: admin
      KC_PASSWORD: admin
      KC_REALM: testing
    services:
#      keycloak0:
#        image: quay.io/keycloak/keycloak:9.0.3
#        env:
#          KEYCLOAK_USER: admin
#          KEYCLOAK_PASSWORD: admin
      keycloak:
        image: registry.redhat.io/rh-sso-7/sso74-openshift-rhel8:7.4-45
        env:
          SSO_ADMIN_USERNAME: admin
          SSO_ADMIN_PASSWORD: admin
          # SSO_HOSTNAME: localhost
        credentials:
          username: ${{ secrets.REGISTRY_REDHAT_IO_USERNAME }}
          password: ${{ secrets.REGISTRY_REDHAT_IO_TOKEN }}

  integration-tests:
    runs-on: ubuntu-22.04
    container: python:3.10
    strategy:
      matrix:
        # service container name
        kc_host: [kc_90, rhsso_74]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: pip install -r requirements-dev.txt
      # install dependencies mentioned in pyproject.toml
      - run: pip install .
      - name: Wait on keycloak to be up
        run: curl -k --connect-timeout 60 --retry 60 --retry-delay 1 --retry-connrefused --retry-max-time 60 $KC_ENDPOINT -v
      # At least it should not crash
      - run: ./main.py --url $KC_ENDPOINT --username admin --password admin --datadir test/data/kcfetcher-latest   --realm-name ci0-realm
    env:
      KEYCLOAK_API_CA_BUNDLE:
      KC_ENDPOINT: http://${{ matrix.kc_host }}:8080
    services:
      kc_90:
        image: quay.io/keycloak/keycloak:9.0.3
        env:
          KEYCLOAK_USER: admin
          KEYCLOAK_PASSWORD: admin
      rhsso_74:
        image: registry.redhat.io/rh-sso-7/sso74-openshift-rhel8:7.4-45
        env:
          SSO_ADMIN_USERNAME: admin
          SSO_ADMIN_PASSWORD: admin
          # SSO_HOSTNAME: localhost
        credentials:
          username: ${{ secrets.REGISTRY_REDHAT_IO_USERNAME }}
          password: ${{ secrets.REGISTRY_REDHAT_IO_TOKEN }}

  # check the package is at least importable
  check-import:
    runs-on: ubuntu-22.04
    container: python:3.10
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # install dependencies mentioned in pyproject.toml
      - run: pip install .
      # from source directory
      - run: python -c 'import kcloader; from kcloader.resource import RealmResource; '
      # from arbitrary directory
      - run: cd /tmp; python -c 'import kcloader; from kcloader.resource import RealmResource; '

  # build whl and upload to pypi.org
  build_whl:
    if: github.ref_type == 'tag'
    needs:
      - unittest
      - integration-tests
      - check-import
    runs-on: ubuntu-22.04
    container: python:3.10
    env:
      TWINE_USERNAME: __token__
      TWINE_PASSWORD: ${{ secrets.PYPI_TWINE_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: echo ref_name=${{ github.ref_name }}
      - run: pip install -r requirements-dev.txt
      - run: python -m build
      #- run: python3 -m twine upload --repository testpypi dist/*

      - run: |-
          PYPROJECT_VERSION=$(grep '^version = ' pyproject.toml | awk '{print $3}' | sed 's/"//g');
          if [ "$PYPROJECT_VERSION" != "${{ github.ref_name }}" ]
          then
            echo "Git tag=${{ github.ref_name }} does not match pyproject.toml version=$PYPROJECT_VERSION" 1>&2
            exit 1
          fi
      - run: python3 -m twine upload dist/*
